systemctl daemon-reload
systemctl status bank_online_payment.service
systemctl start bank_online_payment.service
systemctl enable bank_online_payment.service
systemctl status bank_online_payment.service